Fix: missing vision os simulator model case
google/GoogleUtilities pull request #129
Opened 2023-10-04 06:27 UTC by shimastripe

## WHY

- Environment: Xcode 15.1 Beta

<img width="1167" alt="スクリーンショット 2023-10-04 15 18 14" src="https://github.com/google/GoogleUtilities/assets/15936908/98d8cdc0-c500-4c3b-8d27-80293a3f8063">

- GULAppEnvironmentUtil.m defines `TARGET_OS_VISION` preprocessor macro.
- However I found a missing case and still can't build the GULEnvironment target in visionOS.

## WHAT

- Add vision os simulator model case.

2023-10-04 14:37 UTC, paulb777 commented
@shimastripe Thanks for the PR. We'll need a solution that also builds correctly with Xcode 14. 

Feel free to continue. Otherwise we plan to address before the next Firebase release.

2023-10-05 18:30 UTC, rokon-uddin approved these changes
LGTM

2023-10-05 21:23 UTC, andrewheard requested changes
Thanks, @shimastripe! I think checking `defined(TARGET_OS_VISION)` will fix the warning on CI. Just let me know if you'd prefer me to make the change. Either way, thank you for the PR!

2023-10-05 21:23 UTC, andrewheard commented on GoogleUtilities/Environment/GULAppEnvironmentUtil.m
> +#elif TARGET_OS_VISION
I think changing this to `#elif defined(TARGET_OS_VISION) && TARGET_OS_VISION` will fix:
```
warning: 'TARGET_OS_VISION' is not defined, evaluates to 0 [-Wundef-prefix=TARGET_OS_]
```
-- https://github.com/google/GoogleUtilities/actions/runs/6402537262/job/17393389158?pr=129#step:6:415

2023-10-05 23:16 UTC, andrewheard commented
Thanks for pointing this out! This is now resolved in https://github.com/google/GoogleUtilities/pull/132.

2023-10-05 23:16 UTC, closed without merging